     - name: check apache and if not present then install
       apt:
        name: "{{ package_name }}"
        state: latest
        update_cache: yes

     - name: check the service and make sure that apache in started
       service:
         name: "{{ service_name }}"
         enabled: yes
         state: started

     - name: copy index.html to destination path /var/www/html
       copy:
        src: "{{ index_file }}"
        dest: "{{ document_root }}{{ index_file }}"

     - name: copy apache configuration of is presentin the /var/www/html
       template:
        src: kaleem.conf
        dest: /etc/apache2/sites-available/kaleem.conf
       notify: restart apache2


